// 鑷姩鐢熸垚锛歸eapon_fusion_suggestions.csv -> Evolution 姝﹀櫒鑽夋
// 璇存槑锛歴tatus=寤鸿 鐨勬潯鐩槸鏍规嵁鏉愭枡鍜屾晥鏋滅殑鑽夋鍙傛暟
// 鎻愮ず锛歵ier 褰撳墠涓烘暟鍊?2锛屽搴?WEAPON_TIER.EVOLUTION
export const WEAPON_EVOLUTION_DRAFT = [
    {
        id: 'dark_spore_swarm',
        name: '鏆楀缇?,
        tier: 2,
        damage: 1.4,
        interval: 45,
        speed: 6.5,
        radius: 12,
        color: '#365996',
        lifetime: 150,
        piercing: false,
        vulnerability: 0.25,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '鍒嗚瀛愬脊 + 鏄撲激',
        sources: ['cell', 'dark'],
        status: '鐜版湁'
    },
    {
        id: 'flame_spore_swarm',
        name: '鐐庡缇?,
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#908c55',
        lifetime: 120,
        piercing: false,
        burnDuration: 300,
        burnDamagePerFrame: 0.083333,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '鍒嗚瀛愬脊 + 鐕冪儳DOT',
        sources: ['cell', 'fire'],
        status: '鐜版湁'
    },
    {
        id: 'ice_shard_swarm',
        name: '鍐板睉缇?,
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#10bfd5',
        lifetime: 120,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '鍒嗚瀛愬脊 + 鍐荤粨',
        sources: ['cell', 'frost'],
        status: '鐜版湁'
    },
    {
        id: 'wraith_swarm',
        name: '骞界兢',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 10,
        radius: 12,
        color: '#1f769a',
        lifetime: 120,
        piercing: true,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '鍒嗚瀛愬脊 + 绌块€?,
        sources: ['cell', 'ghost'],
        status: '鐜版湁'
    },
    {
        id: 'prism_swarm',
        name: '妫卞厜缇?,
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#90d9aa',
        lifetime: 120,
        piercing: false,
        blindChance: 0.5,
        blindDuration: 180,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '鑷寸洸 + 鍒嗚瀛愬脊',
        sources: ['cell', 'light'],
        status: '鐜版湁'
    },
    {
        id: 'spark_spore_swarm',
        name: '鐢靛缇?,
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#90d955',
        lifetime: 120,
        piercing: false,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '杩為攣闂數 + 鍒嗚瀛愬脊',
        sources: ['cell', 'lightning'],
        status: '鐜版湁'
    },
    {
        id: 'plague',
        name: '鐦熺柅',
        tier: 2,
        damage: 0.6,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#6f7a66',
        lifetime: 120,
        piercing: false,
        effects: '涓瘨DOT + 鍒嗚瀛愬脊',
        sources: ['cell', 'poison'],
        status: '鐜版湁'
    },
    {
        id: 'radiation_beam',
        name: '杈愬皠灏勭嚎',
        tier: 2,
        damage: 0.8,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#7CFC00',
        lifetime: 120,
        piercing: false,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '灏勭嚎AOE + 鍒嗚瀛愬脊',
        sources: ['cell', 'ray'],
        status: '鐜版湁'
    },
    {
        id: 'overgrowth',
        name: '钄撳欢',
        tier: 2,
        damage: 0.8,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#567c5f',
        lifetime: 120,
        piercing: false,
        overgrowthDuration: 300,
        overgrowthTriggerStacks: 3,
        overgrowthExplosionRadius: 60,
        overgrowthExplosionMultiplier: 2.5,
        effects: '钄撳欢鍙犲眰 + 鐖嗗彂AOE',
        sources: ['cell', 'rock'],
        status: '鐜版湁'
    },
    {
        id: 'shrapnel_core',
        name: '鐮寸墖鏍?,
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 7,
        radius: 12,
        color: '#70b9b5',
        lifetime: 120,
        piercing: false,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '鍒嗚瀛愬脊 + 楂樹激',
        sources: ['cell', 'steel'],
        status: '鐜版湁'
    },
    {
        id: 'split_wind_swarm',
        name: '瑁傞缇?,
        tier: 2,
        damage: 0.7,
        interval: 23,
        speed: 14,
        radius: 12,
        color: '#10d955',
        lifetime: 120,
        piercing: true,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '鍒嗚瀛愬脊 + 楂橀€?,
        sources: ['cell', 'swift'],
        status: '鐜版湁'
    },
    {
        id: 'blood_spore_swarm',
        name: '琛€瀛㈢兢',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 7,
        radius: 12,
        color: '#565955',
        lifetime: 120,
        piercing: false,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '鍒嗚瀛愬脊 + 鍚歌',
        sources: ['cell', 'vampire'],
        status: '鐜版湁'
    },
    {
        id: 'dark_flame',
        name: '鏆楃劙',
        tier: 2,
        damage: 1.5,
        interval: 45,
        speed: 6.5,
        radius: 5,
        color: '#a53341',
        lifetime: 150,
        piercing: false,
        burnDuration: 300,
        burnDamagePerFrame: 0.083333,
        vulnerability: 0.25,
        effects: '鐕冪儳DOT + 鏄撲激',
        sources: ['dark', 'fire'],
        status: '鐜版湁'
    },
    {
        id: 'frost_corrosion',
        name: '鎬ㄧ伒',
        tier: 2,
        damage: 1.5,
        interval: 45,
        speed: 6.5,
        radius: 5,
        color: '#2666c1',
        lifetime: 150,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        effects: '鍐荤粨 + 璇呭拻',
        sources: ['dark', 'frost'],
        status: '鐜版湁'
    },
    {
        id: 'shadow_wraith',
        name: '鎭剁伒',
        tier: 2,
        damage: 1.5,
        interval: 45,
        speed: 8.5,
        radius: 5,
        color: '#351d86',
        lifetime: 150,
        piercing: true,
        effects: '绌块€?+ 璇呭拻',
        sources: ['dark', 'ghost'],
        status: '鐜版湁'
    },
    {
        id: 'eclipse',
        name: '鏃ヨ殌',
        tier: 2,
        damage: 1.5,
        interval: 45,
        speed: 6.5,
        radius: 5,
        color: '#a58096',
        lifetime: 150,
        piercing: false,
        vulnerability: 0.25,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '鑷寸洸 + 鏄撲激',
        sources: ['dark', 'light'],
        status: '鐜版湁'
    },
    {
        id: 'void_thunder',
        name: '铏氶浄',
        tier: 2,
        damage: 1.5,
        interval: 45,
        speed: 6.5,
        radius: 12,
        color: '#a58041',
        lifetime: 150,
        piercing: false,
        vulnerability: 0.25,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        effects: '杩為攣闂數 + 鏄撲激',
        sources: ['dark', 'lightning'],
        status: '鐜版湁'
    },
    {
        id: 'void_beam',
        name: '铏氱┖灏勭嚎',
        tier: 2,
        damage: 1.4,
        interval: 45,
        speed: 6.5,
        radius: 12,
        color: '#a55341',
        lifetime: 150,
        piercing: false,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '灏勭嚎AOE + 璇呭拻',
        sources: ['dark', 'ray'],
        status: '鐜版湁'
    },
    {
        id: 'cursed_stone',
        name: '鏆楄殌鍦板甫',
        tier: 2,
        damage: 1.4,
        interval: 45,
        speed: 6.5,
        radius: 12,
        color: '#6b234b',
        lifetime: 150,
        piercing: false,
        aoeRadius: 80,
        aoeDamage: 0.8,
        effects: '鍦嗗舰AOE + 璇呭拻',
        sources: ['dark', 'rock'],
        status: '鐜版湁'
    },
    {
        id: 'dark_steel',
        name: '榛戦挗',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 5.5,
        radius: 6,
        color: '#8660a1',
        lifetime: 150,
        piercing: false,
        vulnerability: 0.25,
        effects: '楂樹激 + 鏄撲激',
        sources: ['dark', 'steel'],
        status: '鐜版湁'
    },
    {
        id: 'night_blade',
        name: '澶滃垉',
        tier: 2,
        damage: 1.3,
        interval: 40,
        speed: 8.5,
        radius: 5,
        color: '#268041',
        lifetime: 150,
        piercing: true,
        vulnerability: 0.25,
        effects: '绌块€?+ 鏄撲激',
        sources: ['dark', 'swift'],
        status: '鐜版湁'
    },
    {
        id: 'soul_drain',
        name: '琛€鍜?,
        tier: 2,
        damage: 1.5,
        interval: 45,
        speed: 5.5,
        radius: 5,
        color: '#6b0041',
        lifetime: 150,
        piercing: false,
        effects: '璇呭拻',
        sources: ['dark', 'vampire'],
        status: '鐜版湁'
    },
    {
        id: 'frostfire',
        name: '鐕冮湝',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 8,
        radius: 4,
        color: '#00ccff',
        lifetime: 120,
        piercing: false,
        burnDuration: 1200,
        burnDamagePerFrame: 0.16666666666666666,
        burnColor: '#00ccff',
        vulnerability: 0.25,
        effects: '鐕冪儳DOT + 鏄撲激',
        sources: ['frost', 'fire'],
        status: '鐜版湁'
    },
    {
        id: 'ghost_fire',
        name: '楝肩伀',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 10,
        radius: 4,
        color: '#8f5045',
        lifetime: 120,
        piercing: true,
        burnDuration: 300,
        burnDamagePerFrame: 0.083333,
        effects: '绌块€?+ 鐕冪儳DOT',
        sources: ['fire', 'ghost'],
        status: '鐜版湁'
    },
    {
        id: 'dazzle_flame',
        name: '鐪╁厜鐒?,
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 8,
        radius: 4,
        color: '#ffb355',
        lifetime: 120,
        piercing: false,
        burnDuration: 300,
        burnDamagePerFrame: 0.083333,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '鐕冪儳DOT + 鑷寸洸',
        sources: ['fire', 'light'],
        status: '鐜版湁'
    },
    {
        id: 'plasma_chain',
        name: '绛夌鐏摼',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#ffb300',
        lifetime: 120,
        piercing: false,
        burnDuration: 300,
        burnDamagePerFrame: 0.083333,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        effects: '鐕冪儳DOT + 杩為攣闂數',
        sources: ['fire', 'lightning'],
        status: '鐜版湁'
    },
    {
        id: 'toxic_flame',
        name: '姣掔劙',
        tier: 2,
        damage: 0.75,
        interval: 30,
        speed: 8,
        radius: 4,
        color: '#80b300',
        lifetime: 120,
        piercing: false,
        burnDuration: 300,
        burnDamagePerFrame: 0.083333,
        poisonDuration: 900,
        poisonDamagePerStack: 0.05,
        effects: '鐕冪儳DOT + 涓瘨DOT',
        sources: ['fire', 'poison'],
        status: '鐜版湁'
    },
    {
        id: 'solar_beam',
        name: '澶槼鏉?,
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#ff8600',
        lifetime: 120,
        piercing: false,
        burnDuration: 300,
        burnDamagePerFrame: 0.083333,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '灏勭嚎AOE + 鐕冪儳DOT',
        sources: ['fire', 'ray'],
        status: '鐜版湁'
    },
    {
        id: 'lava',
        name: '鐔斿博鐖?,
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#c5560a',
        lifetime: 120,
        piercing: false,
        burnDuration: 300,
        burnDamagePerFrame: 0.083333,
        aoeRadius: 80,
        aoeDamage: 0.8,
        effects: '鍦嗗舰AOE + 鐕冪儳DOT',
        sources: ['fire', 'rock'],
        status: '鐜版湁'
    },
    {
        id: 'bomb',
        name: '鐐稿脊',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 8,
        radius: 6,
        color: '#ff4500',
        lifetime: 120,
        piercing: false,
        explosionRadius: 100,
        explosionDamage: 2,
        effects: '鐖嗙偢AOE',
        sources: ['steel', 'fire'],
        status: '鐜版湁'
    },
    {
        id: 'inferno',
        name: '鐐肩嫳',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 10,
        radius: 12,
        color: '#cc0000',
        lifetime: 120,
        piercing: true,
        burnDuration: 300,
        burnDamagePerFrame: 0.08333333333333333,
        effects: '绌块€?+ 鐕冪儳DOT',
        sources: ['swift', 'fire'],
        status: '鐜版湁'
    },
    {
        id: 'blood_flame',
        name: '琛€鐒?,
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 7,
        radius: 4,
        color: '#c53300',
        lifetime: 120,
        piercing: false,
        burnDuration: 300,
        burnDamagePerFrame: 0.083333,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        effects: '鐕冪儳DOT + 鍚歌',
        sources: ['fire', 'vampire'],
        status: '鐜版湁'
    },
    {
        id: 'frost_wraith',
        name: '闇滅伒',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 10,
        radius: 4,
        color: '#0f83c5',
        lifetime: 120,
        piercing: true,
        freezeChance: 0.3,
        freezeDuration: 120,
        effects: '绌块€?+ 鍐荤粨',
        sources: ['frost', 'ghost'],
        status: '鐜版湁'
    },
    {
        id: 'white_halo',
        name: '鐧芥檿',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 8,
        radius: 4,
        color: '#80e6d5',
        lifetime: 120,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '鍐荤粨 + 鑷寸洸',
        sources: ['frost', 'light'],
        status: '鐜版湁'
    },
    {
        id: 'ice_chain',
        name: '鍐扮數閾?,
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#80e680',
        lifetime: 120,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        effects: '鍐荤粨 + 杩為攣闂數',
        sources: ['frost', 'lightning'],
        status: '鐜版湁'
    },
    {
        id: 'ice_toxin',
        name: '鍐版瘨',
        tier: 2,
        damage: 0.75,
        interval: 30,
        speed: 8,
        radius: 4,
        color: '#00e680',
        lifetime: 120,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        poisonDuration: 900,
        poisonDamagePerStack: 0.05,
        effects: '鍐荤粨 + 涓瘨DOT',
        sources: ['frost', 'poison'],
        status: '鐜版湁'
    },
    {
        id: 'cold_beam',
        name: '瀵掓潫',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#80b980',
        lifetime: 120,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '灏勭嚎AOE + 鍐荤粨',
        sources: ['frost', 'ray'],
        status: '鐜版湁'
    },
    {
        id: 'glacier',
        name: '鍐板窛闇?,
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#468989',
        lifetime: 120,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        aoeRadius: 80,
        aoeDamage: 0.8,
        effects: '鍦嗗舰AOE + 鍐荤粨',
        sources: ['frost', 'rock'],
        status: '鐜版湁'
    },
    {
        id: 'ice_spike',
        name: '鍐伴敟',
        tier: 2,
        damage: 2.4,
        interval: 80,
        speed: 7,
        radius: 6,
        color: '#60c6e0',
        lifetime: 120,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        effects: '鍐荤粨 + 楂樹激',
        sources: ['frost', 'steel'],
        status: '鐜版湁'
    },
    {
        id: 'blizzard',
        name: '鏆撮闆?,
        tier: 2,
        damage: 0.75,
        interval: 20,
        speed: 12,
        radius: 12,
        color: '#00ccff',
        lifetime: 120,
        piercing: true,
        freezeChance: 0.5,
        freezeDuration: 180,
        vulnerability: 0.25,
        effects: '绌块€?+ 鍐荤粨 + 鏄撲激',
        sources: ['swift', 'frost'],
        status: '鐜版湁'
    },
    {
        id: 'frost_leech',
        name: '瀵掗瓌鍚?,
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 7,
        radius: 4,
        color: '#466680',
        lifetime: 120,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        effects: '鍐荤粨 + 鍚歌',
        sources: ['frost', 'vampire'],
        status: '鐜版湁'
    },
    {
        id: 'holy_wisp',
        name: '鍦ｇ伒',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 10,
        radius: 4,
        color: '#8f9d9a',
        lifetime: 120,
        piercing: true,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '鑷寸洸 + 绌块€?,
        sources: ['ghost', 'light'],
        status: '鐜版湁'
    },
    {
        id: 'phantom_arc',
        name: '骞界數',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 10,
        radius: 12,
        color: '#8f9d45',
        lifetime: 120,
        piercing: true,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        effects: '杩為攣闂數 + 绌块€?,
        sources: ['ghost', 'lightning'],
        status: '鐜版湁'
    },
    {
        id: 'nether_stone',
        name: '鐏靛博',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 10,
        radius: 12,
        color: '#55404f',
        lifetime: 120,
        piercing: true,
        aoeRadius: 80,
        aoeDamage: 0.8,
        effects: '鍦嗗舰AOE + 绌块€?,
        sources: ['ghost', 'rock'],
        status: '鐜版湁'
    },
    {
        id: 'phantom_blade',
        name: '骞藉垉',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 9,
        radius: 6,
        color: '#6f7da5',
        lifetime: 120,
        piercing: true,
        effects: '绌块€?+ 楂樹激',
        sources: ['ghost', 'steel'],
        status: '鐜版湁'
    },
    {
        id: 'shadow_rush',
        name: '褰辩柧',
        tier: 2,
        damage: 0.8,
        interval: 23,
        speed: 14,
        radius: 4,
        color: '#0f9d45',
        lifetime: 120,
        piercing: true,
        effects: '绌块€?+ 楂橀€?,
        sources: ['ghost', 'swift'],
        status: '鐜版湁'
    },
    {
        id: 'blood_wraith',
        name: '琛€褰?,
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 9,
        radius: 4,
        color: '#551d45',
        lifetime: 120,
        piercing: true,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        effects: '绌块€?+ 鍚歌',
        sources: ['ghost', 'vampire'],
        status: '鐜版湁'
    },
    {
        id: 'radiant_arc',
        name: '闂€€鐢靛姬',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#ffff55',
        lifetime: 120,
        piercing: false,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '杩為攣闂數 + 鑷寸洸',
        sources: ['light', 'lightning'],
        status: '鐜版湁'
    },
    {
        id: 'toxic_daze',
        name: '姣掔湬',
        tier: 2,
        damage: 0.75,
        interval: 30,
        speed: 8,
        radius: 4,
        color: '#80ff55',
        lifetime: 120,
        piercing: false,
        poisonDuration: 900,
        poisonDamagePerStack: 0.05,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '涓瘨DOT + 鑷寸洸',
        sources: ['light', 'poison'],
        status: '鐜版湁'
    },
    {
        id: 'sun_lance',
        name: '鏃ュ厜鐭?,
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#ffd255',
        lifetime: 120,
        piercing: false,
        blindChance: 0.5,
        blindDuration: 180,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '鑷寸洸 + 灏勭嚎AOE',
        sources: ['light', 'ray'],
        status: '鐜版湁'
    },
    {
        id: 'crystal_glow',
        name: '闂厜寮?,
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#c5a25f',
        lifetime: 120,
        piercing: false,
        blindChance: 0.5,
        blindDuration: 180,
        aoeRadius: 80,
        aoeDamage: 0.8,
        effects: '鑷寸洸 + 鍦嗗舰AOE',
        sources: ['light', 'rock'],
        status: '鐜版湁'
    },
    {
        id: 'holy_hammer',
        name: '鍦ｉ敜',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 7,
        radius: 6,
        color: '#e0e0b5',
        lifetime: 120,
        piercing: false,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '楂樹激 + 鑷寸洸',
        sources: ['light', 'steel'],
        status: '鐜版湁'
    },
    {
        id: 'flash_strike',
        name: '闂',
        tier: 2,
        damage: 0.8,
        interval: 25,
        speed: 10,
        radius: 4,
        color: '#80ff55',
        lifetime: 120,
        piercing: true,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '绌块€?+ 鑷寸洸',
        sources: ['light', 'swift'],
        status: '鐜版湁'
    },
    {
        id: 'blood_glow',
        name: '琛€杈?,
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 7,
        radius: 4,
        color: '#c58055',
        lifetime: 120,
        piercing: false,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '鑷寸洸 + 鍚歌',
        sources: ['light', 'vampire'],
        status: '鐜版湁'
    },
    {
        id: 'venom_arc',
        name: '姣掔數閾?,
        tier: 2,
        damage: 0.75,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#80ff00',
        lifetime: 120,
        piercing: false,
        poisonDuration: 900,
        poisonDamagePerStack: 0.05,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        effects: '涓瘨DOT + 杩為攣闂數',
        sources: ['lightning', 'poison'],
        status: '鐜版湁'
    },
    {
        id: 'ion_beam',
        name: '绂诲瓙鏉?,
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#ffd200',
        lifetime: 120,
        piercing: false,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '杩為攣闂數 + 灏勭嚎AOE',
        sources: ['lightning', 'ray'],
        status: '鐜版湁'
    },
    {
        id: 'thunder_grit',
        name: '闆烽渿',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#c5a20a',
        lifetime: 120,
        piercing: false,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        aoeRadius: 80,
        aoeDamage: 0.8,
        effects: '杩為攣闂數 + 鍦嗗舰AOE',
        sources: ['lightning', 'rock'],
        status: '鐜版湁'
    },
    {
        id: 'mag_rail',
        name: '纾佽建',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 7,
        radius: 12,
        color: '#e0e060',
        lifetime: 120,
        piercing: false,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        effects: '楂樹激 + 杩為攣闂數',
        sources: ['lightning', 'steel'],
        status: '鐜版湁'
    },
    {
        id: 'storm',
        name: '椋庢毚',
        tier: 2,
        damage: 0.75,
        interval: 20,
        speed: 12,
        radius: 12,
        color: '#ffff00',
        lifetime: 120,
        piercing: true,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        effects: '绌块€?+ 杩為攣闂數',
        sources: ['swift', 'lightning'],
        status: '鐜版湁'
    },
    {
        id: 'leech_arc',
        name: '鍚搁浄閾?,
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 7,
        radius: 12,
        color: '#c58000',
        lifetime: 120,
        piercing: false,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        effects: '杩為攣闂數 + 鍚歌',
        sources: ['lightning', 'vampire'],
        status: '鐜版湁'
    },
    {
        id: 'swamp',
        name: '姣掔垎',
        tier: 2,
        damage: 0.65,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#46a20a',
        lifetime: 120,
        piercing: false,
        poisonDuration: 900,
        poisonDamagePerStack: 0.05,
        aoeRadius: 80,
        aoeDamage: 0.8,
        effects: '涓瘨DOT + 鍦嗗舰AOE',
        sources: ['poison', 'rock'],
        status: '鐜版湁'
    },
    {
        id: 'toxic_spike',
        name: '姣掗拤',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 7,
        radius: 6,
        color: '#60e060',
        lifetime: 120,
        piercing: false,
        poisonDuration: 900,
        poisonDamagePerStack: 0.05,
        effects: '楂樹激 + 涓瘨DOT',
        sources: ['poison', 'steel'],
        status: '鐜版湁'
    },
    {
        id: 'poison_mist',
        name: '姣掗浘',
        tier: 2,
        damage: 0.75,
        interval: 30,
        speed: 10,
        radius: 12,
        color: '#00ff00',
        lifetime: 120,
        piercing: true,
        poisonDuration: 900,
        poisonDamagePerStack: 0.05,
        effects: '绌块€?+ 涓瘨DOT',
        sources: ['swift', 'poison'],
        status: '鐜版湁'
    },
    {
        id: 'ley_beam',
        name: '闇囪崱鏉?,
        tier: 2,
        damage: 0.8,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#c5750a',
        lifetime: 120,
        piercing: false,
        aoeRadius: 80,
        aoeDamage: 0.8,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '灏勭嚎AOE + 鍦嗗舰AOE',
        sources: ['ray', 'rock'],
        status: '鐜版湁'
    },
    {
        id: 'rail_beam',
        name: '杞ㄩ亾鏉?,
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 7,
        radius: 12,
        color: '#e0b360',
        lifetime: 120,
        piercing: false,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '灏勭嚎AOE + 楂樹激',
        sources: ['ray', 'steel'],
        status: '鐜版湁'
    },
    {
        id: 'rapid_beam',
        name: '鐤惧厜鏉?,
        tier: 2,
        damage: 0.7,
        interval: 23,
        speed: 14,
        radius: 12,
        color: '#80d200',
        lifetime: 120,
        piercing: true,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '灏勭嚎AOE + 楂橀€?,
        sources: ['ray', 'swift'],
        status: '鐜版湁'
    },
    {
        id: 'blood_beam',
        name: '琛€鏉?,
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 7,
        radius: 12,
        color: '#c55300',
        lifetime: 120,
        piercing: false,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '灏勭嚎AOE + 鍚歌',
        sources: ['ray', 'vampire'],
        status: '鐜版湁'
    },
    {
        id: 'rift_hammer',
        name: '瑁傚湴閿?,
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 7,
        radius: 12,
        color: '#a6836a',
        lifetime: 120,
        piercing: false,
        aoeRadius: 80,
        aoeDamage: 0.8,
        effects: '楂樹激 + 鍦嗗舰AOE',
        sources: ['rock', 'steel'],
        status: '鐜版湁'
    },
    {
        id: 'sandstorm',
        name: '鐮傛毚',
        tier: 2,
        damage: 0.7,
        interval: 25,
        speed: 10,
        radius: 12,
        color: '#46a20a',
        lifetime: 120,
        piercing: true,
        aoeRadius: 80,
        aoeDamage: 0.8,
        effects: '绌块€?+ 鍦嗗舰AOE',
        sources: ['rock', 'swift'],
        status: '鐜版湁'
    },
    {
        id: 'blood_quake',
        name: '琛€闇?,
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 7,
        radius: 12,
        color: '#8b230a',
        lifetime: 120,
        piercing: false,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        aoeRadius: 80,
        aoeDamage: 0.8,
        effects: '鍦嗗舰AOE + 鍚歌',
        sources: ['rock', 'vampire'],
        status: '鐜版湁'
    },
    {
        id: 'rapid_lance',
        name: '鐤炬灙',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 9,
        radius: 6,
        color: '#60e060',
        lifetime: 120,
        piercing: true,
        effects: '绌块€?+ 楂樹激',
        sources: ['steel', 'swift'],
        status: '鐜版湁'
    },
    {
        id: 'blood_hammer',
        name: '琛€妲?,
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 6,
        radius: 6,
        color: '#a66060',
        lifetime: 120,
        piercing: false,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        effects: '楂樹激 + 鍚歌',
        sources: ['steel', 'vampire'],
        status: '鐜版湁'
    },
    {
        id: 'swift_leech',
        name: '杩呭惛',
        tier: 2,
        damage: 0.8,
        interval: 25,
        speed: 9,
        radius: 4,
        color: '#468000',
        lifetime: 120,
        piercing: true,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        effects: '绌块€?+ 鍚歌',
        sources: ['swift', 'vampire'],
        status: '鐜版湁'
    },
];
